### ISSUE TITLE
Release 2.0 please

### ISSUE THREAD

**Issue by gyst** [plone/plone.app.blocks#15] opened 2015-03-06 16:08 UTC
@jensens merged the work done in the mosaicsprint last year to master. This is great, because this work contains many fixes. Especially tiles break in plone5 without these fixes.

We're preparing a release for ploneintranet now and need plone.app.blocks 2.0. @garbas @vangheem @ericof @calvinhp you're listed on pypi, can one of you please cut a release?

I already checked with @hvelarde that collective.cover has a pin in place on 1.x so it won't break.

**Comment by hvelarde** [comment] 2015-03-06 17:26
before doing that, please update the changelog to include a detailed description on all changes done in the package; this way we will be able to update collective.cover also.

**Comment by hvelarde** [comment] 2015-03-06 17:30
also, note that the [Travis CI build for Plone 5.0 is broken](https://travis-ci.org/plone/plone.app.blocks/jobs/53206131); we need to guarantee that tests are passing there also.

**Comment by datakurre** [comment] 2015-03-06 17:47
I can update the changelog tomorrow.

**Comment by jensens** [comment] 2015-03-06 17:50
well, 5.0 is broken, because the test setup is broken::

    Error: Error downloading extends for URL https://launchpad.net/plone/5.0/5.0a3/+download/Plone-5.0a3-UnifiedInstaller.tgz: ('http error', 404, 'Not Found', <httplib.HTTPMessage instance at 0x7f81be8e3488>)

I run the tests against current coredev checkouts and versions and all passed on my machine.

I'd say this is a fix to be done in https://github.com/collective/buildout.plonetest/

**Comment by hvelarde** [comment] 2015-03-06 18:27
I though @do3cc has fixed that.

**Comment by datakurre** [comment] 2015-03-06 19:08
[Updated changelog](https://github.com/plone/plone.app.blocks/blob/master/CHANGELOG.rst)

Refactored Travis-build to use container based Travis-builds with support for cached eggs folder betweend builds (builds after the first one will be immediate).

**Comment by datakurre** [comment] 2015-03-06 19:23
[Green and fast for Plone 4-latest and 5-latest](https://travis-ci.org/plone/plone.app.blocks/builds/53384883)

**Comment by hvelarde** [comment] 2015-03-06 19:24
awesome!

**Comment by datakurre** [comment] 2015-03-06 19:33
@hvelarde Oh, sorry. I was too fast. I broke the regexp in Travis configuration and tests were not run for Plone 5. Only for Plone 4 twice.

**Comment by gyst** [comment] 2015-03-06 20:46
I filed an issue for plonetest on the travis breakage. https://github.com/collective/buildout.plonetest/issues/10

**Comment by datakurre** [comment] 2015-03-07 02:10
Ahem, maybe we should fix those Plone 5 test errors before the release. I'll try to pick the low hanging fruits at first.

**Comment by datakurre** [comment] 2015-03-07 04:07
There's still some rendering differences and then some real issues in tests with Plone 5.

If someone knows the differences in LXML version and settings between Plone 4 and Plone 5, for me it would be ok that we would default to Plone 5 versions and settings also on Plone 4 with p.a.blocks 2.x.

I'll try to look into the remaining real issues later.

**Comment by datakurre** [comment] 2015-03-07 07:49
Almost there. Plone.app.theming is mutatming the HTML serializer doctype (even when it's disabled), which changes rendering results. I'll try to file a pull into p.a.theming about this. So, Plone 5 tests will not go green before that's fixed.

**Comment by datakurre** [comment] 2015-03-07 07:50
Also, there's still some real issues remaining, but those are easier to solve now, when I can disable the noise caused by p.a.theming.

**Comment by datakurre** [comment] 2015-03-07 09:18
Done. Plone 5 build would be green if the referenced issues are fixed in plone.app.theming and plone.protect.

**Comment by gyst** [comment] 2015-03-07 12:52
Thanks for the work on this, Asko. I really need this release in order to be able to do the initial Mercury release of Plone Intranet this month. Much appreciated.

--
   Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

   s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Comment by do3cc** [comment] 2015-03-09 11:52
This thing on travis is quite hard to debug because the .travis.yml is oh so clever with sed.
I don't know what is wrong here with plonetest.
Mabye replacing the sed hack with explicit buildout files makes this thing debuggable again.
also, extends can be overridden like this: `bin/buildout -c bla "buildout:extends=plone5.cfg" Maybe this adds readability too

**Comment by datakurre** [comment] 2015-03-09 12:19
@do3cc Just do it.

**Comment by hvelarde** [comment] 2015-03-09 13:51
the build is fixed now; the tests are still failing under Plone 5.0

**Comment by datakurre** [comment] 2015-03-09 17:20
@hvelarde Thanks. As I mentioned before, the failures on Plone 5 should be fixed in p.a.theming and p.protect (I linked my pull requestes earlier).

**Comment by jensens** [comment] 2015-03-10 17:27
thanks, both are merged meanwhile

**Comment by datakurre** [comment] 2015-04-14 13:44
Green https://travis-ci.org/plone/plone.app.blocks

**Closed** 2015-06-10 07:46 UTC
