### ISSUE TITLE
Additional line jumps in TinyMCE

### ISSUE THREAD

**Issue by frapell** [plone/plone.app.blocks#63] opened 2018-03-28 22:50 UTC
@datakurre Why is there a `pretty_print=True` in https://github.com/plone/plone.app.blocks/blob/0a7e40f9bcfc0cc3cdd4a8ad1dbed7b9a3d2ee75/plone/app/blocks/layoutbehavior.py#L309

When I inspect the `set` method for `TransientTileDataManager` in `plone.tiles`, I see this data coming in:
```
(Pdb) pp data
{'content': u'<p>Line 1</p><p>Line 2</p>'}
```

However when inspecting the `get` I see this:
```
(Pdb) data
{'content': u'<p>Line 1</p>\n<p>Line 2</p>'}
```

In latest TinyMCE this makes it put additional `<br />` all over the place when moving richtext tiles around...

Removing the `pretty_print` makes it return the same data as it went in, and doesn't provoke this issue with TinyMCE. Is there a reason to keep it?

**Comment by datakurre** [comment] 2018-03-29 03:41
That’s terrible from TinyMCE (to add br tags outside blocks).

That said, please, remove the pretty print. It has no real function. Sorry for the inconvenience caused by that and thanks for finding that out. (It only makes the content look prettier eg for REST API.)

**Comment by petschki** [comment] 2018-07-02 13:33
fixed in https://github.com/plone/plone.app.blocks/releases/tag/4.1.2

**Closed by petschki** 2018-07-02 13:33 UTC
